name: ESLint & CodeQL Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 11 * * 6'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  lint-and-scan:
    name: Run ESLint and Upload SARIF
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install pnpm (official action) and Node 20 for CodeQL v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      # 3. Install dependencies and SARIF formatter
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -D eslint@8.10.0 \
                    @microsoft/eslint-formatter-sarif@3.1.0

      # 4. Run ESLint, emit SARIF
      - name: Run ESLint → SARIF
        run: |
          npx eslint . \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
            || echo "ESLint completed with reports"

      # 5. Debug: confirm where the SARIF landed
      - name: Debug workspace layout
        run: |
          echo "Repository root is $GITHUB_WORKSPACE"
          ls -R .

      # 6. Upload SARIF to CodeQL (glob under repo root)
      - name: Upload SARIF to CodeQL
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: '**/*.sarif'
          wait-for-processing: true
