name: ESLint
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '39 11 * * 6'

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      # Explicitly install pnpm globally first
      - name: Install pnpm globally
        run: npm install -g pnpm@latest-10
        
      # Verify pnpm is installed
      - name: Verify pnpm installation
        run: pnpm --version
          
      - name: Install dependencies
        run: pnpm install
          
      - name: Install ESLint and SARIF formatter
        run: |
          pnpm add -D eslint@8.10.0
          pnpm add -D @microsoft/eslint-formatter-sarif@3.1.0
          
      - name: Run ESLint
        run: |
          pnpm eslint . \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
            || echo "ESLint failed, but continuing workflow"
            
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
