name: ESLint
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '39 11 * * 6'  # Fixed spacing in cron syntax

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci || npm install
          
      - name: Install ESLint and SARIF formatter
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          
      - name: Run ESLint
        run: |
          # Make sure the output directory exists
          mkdir -p sarif-reports
          
          # Run ESLint with more flexible configuration approach
          npx eslint . \
            --ext .js,.jsx,.ts,.tsx \
            --format @microsoft/eslint-formatter-sarif \
            --output-file sarif-reports/eslint-results.sarif || true
            
      - name: Debug file existence
        run: |
          ls -la sarif-reports/
          
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: sarif-reports/eslint-results.sarif
          wait-for-processing: true
